### ISSUE TITLE
Figure out and set up the best deployment and CI/CD option

### ISSUE THREAD

**Issue by misterpeddy** [misterpeddy/hands-down#5]
Requirements:
* Shouldn't have to pay 
* Should be closely mirroring our dev setup (running `npm start` and nothing else)
* Should be able to set up staging and prod instances (not necessary at first)
* Should be able to push to deploy

**Comment by Berkmann18** [comment]
For CI/CDs, we could use either GitHub Actions (e.g. `actions/setup-node`), all the other options I've used aren't free for teams (e.g. TravisCI, CircleCI, Netlify's CI, Azure Pipelines).

For the deployment, it depends on what is going to be hosted:
- Static site content: GitHub Pages, Netlify, Now.sh/ZEIT, Surge, Firebase
- NodeJS server: Heroku, Digital Ocean, Linode, Firebase
