### ISSUE TITLE
Add privacy policy and Terms of Service

### ISSUE THREAD

**Issue by misterpeddy** [misterpeddy/hands-down#53]
Some examples would be https://prinsec.com/terms-of-use or https://www.jrtapsell.co.uk/privacy.html

**Comment by Berkmann18** [comment]
Should we also have a security policy (and [what goes with it](https://securitytxt.org))? If so, what email we'll use for the contact section?

**Comment by HugoTse** [comment]
I think we're good as long as we're not collecting personally identifiable information. Are we providing an email so that people can raise their concerns? Suggest improvements?

**Comment by Berkmann18** [comment]
> I think we're good as long as we're not collecting personally identifiable information

From a GDPR standpoint, we're pretty much good to go (although we don't have any GDPR documentation filled or anyone in charge of such documentation).

The email was mainly for the security policy and to have contact information for those who which to submit vulnerability reports or anything of the sort.
You can see what we have so far on #56.

**Comment by HugoTse** [comment]
> > I think we're good as long as we're not collecting personally identifiable information
> 
> From a GDPR standpoint, we're pretty much good to go (although we don't have any GDPR documentation filled or anyone in charge of such documentation).
> 
> > Are we providing an email so that people can raise their concerns? Suggest improvements?
> 
> Essentially yes, that way, anyone who discovered vulnerability can contact appropriately without having to go the public route.

Sounds great!

**Comment by HugoTse** [comment]
> > > I think we're good as long as we're not collecting personally identifiable information
> > 
> > 
> > From a GDPR standpoint, we're pretty much good to go (although we don't have any GDPR documentation filled or anyone in charge of such documentation).
>
> In that case, I reckon we can do away with mentioning privacy. I don't foresee users being able to escalate issues to involve regulations.
> > > Are we providing an email so that people can raise their concerns? Suggest improvements?
> > 
> > 
> > Essentially yes, that way, anyone who discovered vulnerability can contact appropriately without having to go the public route.
> 
> Sounds great!
