### ISSUE TITLE
Set up a Github Project with milestones

### ISSUE THREAD

**Issue by misterpeddy** [misterpeddy/hands-down#8]
A few milestones I can think of:
* dark launch (app is up but we don't announce anywhere)
* alpha launch (we invite a few friends each to try it out and we measure metrics related to how well the app is working (precision, recall rates -- tbd if we can actually collect this data) )
* beta launch (we invite a couple small communities to try it out, we measure product metrics like engagement, retention, DAU, etc.)
* GA launch (make a big splash, invite HH, various mailing lists at work and school - at this point either it's something we're all proud of and want to brag about or we can call it a day and go home :) )

**Comment by amirhmk** [comment]
I think you need to give out access or do this yourself. You should be able to create a new board from the "Projects" tab with a few different template options (Kanban with automated reviews, and I add a "In Review" Section too)

**Comment by misterpeddy** [comment]
You're added as collaborator - lmk if that doesn't give you write permissions for project boards! 
I want to be able to have 4 collections of issues corresponding to the milestones - that way we can put every issue in whatever milestone it's needed for. Unsure whether it should be 4 separate projects or 4 boards..
Wanna take a stab at setting it up?

**Comment by amirhmk** [comment]
> You're added as collaborator - lmk if that doesn't give you write permissions for project boards!
> I want to be able to have 4 collections of issues corresponding to the milestones - that way we can put every issue in whatever milestone it's needed for. Unsure whether it should be 4 separate projects or 4 boards..
> Wanna take a stab at setting it up?

Yep I was able to create a board now, so this board is what I thought would be the "Release Board". I think the milestones are good, but do you think we would need 4 separate board for them? I would imagine this spring (board) to be completed within 2 weeks, would that be a fair assumptions? 

Re milestones, one option is to add Labels to them?

**Comment by Berkmann18** [comment]
Milestones (at least on GH) are independent to GH Project boards, you could easily have a single board where several issues were associated with different milestones.
I personally think it would be better to have the "Alpha" release as a milestone (which can be created on https://github.com/misterpeddy/hands-down/milestones/new) and the project is the backlog, which could be complemented by area/role specific boards or sprint ones.

As for labels, we could use something like on [TemplateJS](https://github.com/Berkmann18/TemplateJS/labels), i.e. labels for issue/PR: status, type, priority.
